<?php
// Portuguese (Brazil)
return [
    'number' => 'Referência',
    'date' => 'Data de cobrança',
    'time' => 'Tempo de cobrança',
    'due' => 'Data de Vencimento',
    'to' => 'Faturamento para',
    'from' => 'Faturamento de',
    'product' => 'Produto',
    'qty' => 'Qtde',
    'price' => 'Preço',
    'discount' => 'Desconto',
    'vat' => 'ICMS',
    'total' => 'Total',
    'page' => 'Página',
    'page_of' => 'de',
];