<?php
// German (Deutsch)
return [
    'number'   => 'Rechnungsnummer',
    'date'     => 'Rechnungsdatum',
    'time'     => 'Rechnungs-Uhrzeit',
    'due'      => 'Fälligkeitsdatum',
    'to'       => 'Rechnungsempfänger',
    'from'     => 'Rechnung von',
    'product'  => 'Produkt',
    'qty'      => 'Menge',
    'price'    => 'Preis',
    'discount' => 'Rabatt',
    'vat'      => 'MwSt',
    'total'    => 'Gesamt',
    'page'     => 'Seite',
    'page_of'  => 'von',
];