<?php
// English
return [
    'number'   => 'Reference',
    'date'     => 'Billing date',
    'time'     => 'Billing time',
    'due'      => 'Due date',
    'to'       => 'Billing to',
    'from'     => 'Billing from',
    'product'  => 'Product',
    'qty'      => 'Qty',
    'price'    => 'Price',
    'discount' => 'Discount',
    'vat'      => 'Vat',
    'total'    => 'Total',
    'page'     => 'Page',
    'page_of'  => 'of',
];
