<?php
return [
    'number' => 'Referencia',
    'date' => 'Fecha',
    'due' => 'Fecha de vencimiento',
    'time' => 'Fecha de factura',
    'to' => 'Facturación a',
    'from' => 'Nuestra información',
    'product' => 'Producto',
    'qty' => 'Cantidad',
    'price' => 'Precio',
    'discount' => 'Descuento',
    'vat' => 'Impuestos',
    'total' => 'Total de',
    'page' => 'Página',
    'page_of' => 'de',
];