<?php
// Italian
return [
    'number'   => 'Riferimento',
    'date'     => 'Data di fatturazione',
    'due'      => 'Scadenza',
    'to'       => 'Fatturazione per',
    'from'     => 'Nostre informazioni',
    'product'  => 'Prodotto',
    'qty'      => 'Quantità',
    'price'    => 'Prezzo',
    'discount' => 'Sconto',
    'vat'      => 'Imposta',
    'total'    => 'Totale',
    'page'     => 'Pagina',
    'page_of'  => 'di',
];
