<?php
// Dutch
return [
    'number'   => 'Referentie',
    'date'     => 'Aangemaakt',
    'time'     => 'Tijd',
    'due'      => 'Vervaldatum',
    'to'       => 'Begunstigde',
    'from'     => 'Onze gegevens',
    'product'  => 'Product',
    'qty'      => 'Aantal',
    'price'    => 'Prijs',
    'discount' => 'Korting',
    'vat'      => 'BTW',
    'total'    => 'Totaal',
    'page'     => 'Pagina',
    'page_of'  => 'van',
];
