<?php
// Romanian
return [
    'number'   => 'Nr. facturii',
    'date'     => 'Data facturii',
    'time'     => 'Ora facturii',
    'due'      => 'Data scadenței',
    'to'       => 'Client',
    'from'     => 'Furnizor',
    'product'  => 'Produs',
    'qty'      => 'Cantitate',
    'price'    => 'Preț',
    'discount' => 'Reducere',
    'vat'      => 'T.V.A.',
    'total'    => 'Total',
    'page'     => 'Pagina',
    'page_of'  => 'din',
];
